openapi: 3.2.0
info:
  title: Dataverse Notifications API
  description: Open source research data repository software.
  version: 6.10.1
tags:
- name: Notifications
paths:
  /notifications/all:
    get:
      operationId: Notifications_getAllNotificationsForUser
      parameters:
      - name: inAppNotificationFormat
        in: query
        schema:
          type: boolean
      - name: limit
        in: query
        schema:
          format: int32
          type: integer
      - name: offset
        in: query
        schema:
          format: int32
          type: integer
      - name: onlyUnread
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications get all notifications for user
      x-summary-source: derived
  /notifications/mutedEmails:
    get:
      operationId: Notifications_getMutedEmailsForUser
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications get muted emails for user
      x-summary-source: derived
  /notifications/mutedEmails/{typeName}:
    put:
      operationId: Notifications_muteEmailsForUser
      parameters:
      - name: typeName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications mute emails for user
      x-summary-source: derived
    delete:
      operationId: Notifications_unmuteEmailsForUser
      parameters:
      - name: typeName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications unmute emails for user
      x-summary-source: derived
  /notifications/mutedNotifications:
    get:
      operationId: Notifications_getMutedNotificationsForUser
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications get muted notifications for user
      x-summary-source: derived
  /notifications/mutedNotifications/{typeName}:
    put:
      operationId: Notifications_muteNotificationsForUser
      parameters:
      - name: typeName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications mute notifications for user
      x-summary-source: derived
    delete:
      operationId: Notifications_unmuteNotificationsForUser
      parameters:
      - name: typeName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications unmute notifications for user
      x-summary-source: derived
  /notifications/unreadCount:
    get:
      operationId: Notifications_getUnreadNotificationsCountForUser
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications get unread notifications count for user
      x-summary-source: derived
  /notifications/{id}:
    delete:
      operationId: Notifications_deleteNotificationForUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications delete notification for user
      x-summary-source: derived
  /notifications/{id}/markAsRead:
    put:
      operationId: Notifications_markNotificationAsReadForUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          description: OK
      tags:
      - Notifications
      summary: Notifications mark notification as read for user
      x-summary-source: derived
