openapi: 3.2.0
info:
  title: Dataverse Mail API
  description: Open source research data repository software.
  version: 6.10.1
tags:
- name: Mail
paths:
  /mail/notifications:
    get:
      operationId: Mail_sendMail
      responses:
        '200':
          description: OK
      tags:
      - Mail
      summary: Mail send mail
      x-summary-source: derived
