openapi: 3.2.0
info:
  title: Dataverse Sendfeedback API
  description: Open source research data repository software.
  version: 6.10.1
tags:
- name: Send Feedback
paths:
  /sendfeedback:
    post:
      operationId: SendFeedbackAPI_submitFeedback
      responses:
        '200':
          description: OK
      tags:
      - Send Feedback
      summary: Send feedback API submit feedback
      x-summary-source: derived
